#include <iostream>

/*
 * Default constructor is a constructor that accepts no arguments.
 * This is constuctor with no arguments.
 */

class Foo {
    private:
        int temp {};

    public:
        Foo()
        {
            std::cout << "Default constructor is called!" << std::endl;
        }

        /*
         * This is invalid if we have default constructor.
         * As compiler gets confused between default function Foo() and
         * Foo(int a = 10) have default parameter.
         *
         * If all of the parameters are default parameters then that constructors
         * is default constructors.
         */
        // Foo(int a = 10): temp(a) {}
};

/*
 * Value initialization and default initialization in class types.
 *
 * 1. If class have default constructor then, both value initialization and
 *    default initialization will call the default constructor.
 *    Foo foo{};    // value initialization, calls default constructor
 *    Foo foo;      // default initialization, calls default constructor.
 * Prefer value initialization over default initialization for all class types.
 *
 * 2. As of other functions, constructors also can have default parameters.
 */

/*
 * Constructor overloading
 *
 * constructors are functions henec that also can be overloaded.
 * So, we can have multiple constructors that we can construct our objects in
 * multiple ways.
 *
 * But each class can have only one default constructor, if there are multiple
 * then compiler gets confused.
 *
 * Prefer, explicitly defaulted default constructor over implicit default
 * constructor.
 *
 * Note:
 *      If we have user defined default constructor like;
 *      Foo(){}, then if we value initialize object then objects will be default
 *      initialized. Members of object with no initialization will have garbage.
 *
 *      Implicit default constructor and explicit defaulted default constructor
 *      will value initialize the data members even if they dont have value
 *      initializers.
 */

class Temp
{
    private:
        int a {};

    public:
        Temp()
        {
            std::cout << "This is default constructor!" << std::endl;
        }

        Temp(int num1 = 10, int num2 = 20): a{num1} {
            std::cout << "This is also default constructor!" << std::endl;
        }
};

/*
 * Implicit default constructor
 *
 * If non-aggregate type class type object has no user-defined constructors,
 * the compiler will generate a public default constructor. So class can be value
 * or default initialized.
 * This type of constructor is called "implicit default constructor".
 *
 * Implicit default constructor has no parameters, member initializer list,
 * and no statements in the body.
 */

/*
 * Using "= default" to generate an explicitly defaulted constructor.
 *
 * While compiler generates implicit default constructor, we can also tell the
 * compiler to generate a default constructor for us.
 *
 * This constructor is called as "explicitly defaulted default constructor".
 * It can be generated by using the "= default" syntax.
 */

class Too {
    private:
        int temp {};

    public:
        Too() = default; // generates an explicitly defaulted default constructor

        // Here we have user defined constructor, so implicit default construtor
        // will not be generated. Hence we have generated one explicitly above.
        Too(int num): temp{num} {}
};

int main()
{
    Foo foo {};         // no initialization values, calls default constructor.

    // This will gerenerate error, because call to default constructor is ambigious
    // Temp temp1 {};
    return 0;
}
